// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVebA9TZniDv5oj0_RvFL33VM7GSjHE68',
    appId: '1:132035547677:web:116cde2cfcc21b6909acf4',
    messagingSenderId: '132035547677',
    projectId: 'scanplakdatabase-4d7b4',
    authDomain: 'scanplakdatabase-4d7b4.firebaseapp.com',
    storageBucket: 'scanplakdatabase-4d7b4.firebasestorage.app',
    measurementId: 'G-MV50C8RYJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0z-tGy6pX0NrbFJrDYM9NEeKcX18Fo8',
    appId: '1:132035547677:android:251622342c48e37109acf4',
    messagingSenderId: '132035547677',
    projectId: 'scanplakdatabase-4d7b4',
    storageBucket: 'scanplakdatabase-4d7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmKMb-lpX6BraD7uFkw04etdsvDkbDA7Q',
    appId: '1:132035547677:ios:c91e4e97063ac47709acf4',
    messagingSenderId: '132035547677',
    projectId: 'scanplakdatabase-4d7b4',
    storageBucket: 'scanplakdatabase-4d7b4.firebasestorage.app',
    iosBundleId: 'com.example.skanPlak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmKMb-lpX6BraD7uFkw04etdsvDkbDA7Q',
    appId: '1:132035547677:ios:c91e4e97063ac47709acf4',
    messagingSenderId: '132035547677',
    projectId: 'scanplakdatabase-4d7b4',
    storageBucket: 'scanplakdatabase-4d7b4.firebasestorage.app',
    iosBundleId: 'com.example.skanPlak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVebA9TZniDv5oj0_RvFL33VM7GSjHE68',
    appId: '1:132035547677:web:d4a4d5944e4b5ae109acf4',
    messagingSenderId: '132035547677',
    projectId: 'scanplakdatabase-4d7b4',
    authDomain: 'scanplakdatabase-4d7b4.firebaseapp.com',
    storageBucket: 'scanplakdatabase-4d7b4.firebasestorage.app',
    measurementId: 'G-YDWZD07P30',
  );
}
